Bash grep
mkarpenkospb/SDhomework pull request #2
Opened 2020-03-11 06:05 UTC by mkarpenkospb

Commons CLI оказался удобным и просто настраиваемым.

Так как изначально я, скорее всего очень криво реализовала pipe, тут он не работает. 
1) Кажется неправильным переписывать один и тот же код в зависимости от того читаю я из файла или нет.
2) Нужно переписывать парсинг, я предположила, что так как влуги мы всё равно не реализуем, аргументов у фнункций в pipeline быть не может кроме того, что передается через pipe.

2020-03-30 15:29 UTC, ottergottaott requested changes
По функциональности в основном хорошо, но потенциальные ошибки при вводе не проверяются:
```java
> grep -A plugin build.gradle # завершает работу с исключением,
# что очень грубо. Лучше мягко сообщить, но продолжить работу
Exception in thread "main" java.lang.NumberFormatException: For input string: "plugin"

> grep -A -1 plugin build.gradle # отработает так, будто все ок, стоит сделать проверку

> grep -A # снова падаем с исклюением
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
```

Да, пайпы придется доделать. По коду оставил замечания ниже.

2020-03-30 15:29 UTC, aleksZubakov commented on src/main/java/itmo/karpenko/cli/InnerGrep.java
> + * Данный класс повторяет функцию grep
Нет, утилиту grep он не совсем повторяет :)

2020-03-30 15:29 UTC, aleksZubakov commented on src/main/java/itmo/karpenko/cli/InnerGrep.java
> +    int nLines = 0;
`private`

2020-03-30 15:29 UTC, aleksZubakov commented on src/main/java/itmo/karpenko/cli/InnerGrep.java
> +    CommandLineParser cmdLinePosixParser = new PosixParser();
Это даже можно сделать `private final static`, т.к. не будет меняться от объекта к объекту

2020-03-30 15:29 UTC, aleksZubakov commented on src/main/java/itmo/karpenko/cli/InnerGrep.java
> +        Option optW = new Option("w", false, "word");
И это можно унести в `static` секцию, чтобы более явно обозначить, что эти опции будут одинаковые для всех экземпляров.

2020-03-30 15:29 UTC, aleksZubakov commented on src/main/java/itmo/karpenko/cli/InnerGrep.java
> +                                cnt = 0;
Очень хочется каким-нибудь образом упростить этот метод, потому что читать код в 7 вложенных друг в друга блоках крайне сложно.

Можно попробовать выделить отдельные логические блоки в методы, попробовать инвертировать условия (иногда это делает код менее вложенным), мб, даже имеет смысл спокойно переписать заново.  В общем, что угодно, но не оставлять все в таком виде

2020-03-30 15:29 UTC, aleksZubakov commented on src/main/java/itmo/karpenko/cli/InnerGrep.java
> +    String p2N = "";
Из такого названия не понятно ничего

2020-03-30 15:29 UTC, aleksZubakov commented on src/main/java/itmo/karpenko/cli/InnerGrep.java
> +            pattern = Pattern.compile(toFind, Pattern.CASE_INSENSITIVE);
`Pattern.compile` не бесплатный, лучше и вместо этих паттернов сделать static поля, чтобы создались один раз, а тут писать условное:
```java
pattern = commandLine.hasOption("I") ? this.CASE_INSENSITIVE : this.CASE_SENSITIVE
```

2020-06-08 11:39 UTC, mkarpenkospb commented on src/main/java/itmo/karpenko/cli/InnerGrep.java
> +                                cnt = 0;
Я разделила так как появились пайпы, но все равно выглядит немного грязно  -- я пытаюсь повторить форматирование вывода grep. Теперь всё полностью цветное. Осчитываю, когда пора добавлять "--", нужно ли добавлять имя файла и так далее.

2020-06-08 11:39 UTC, mkarpenkospb commented on src/main/java/itmo/karpenko/cli/InnerGrep.java
> +            pattern = Pattern.compile(toFind, Pattern.CASE_INSENSITIVE);
Запуталась немного, что такое this тут? Всё равно один раз компилируется шаблон для каждого нового шаблона.

2020-06-08 11:43 UTC, mkarpenkospb commented
Исправила замечания, но с компиляцией шаблона не поняла.

2020-06-08 21:57 UTC, aleksZubakov commented on src/main/java/itmo/karpenko/cli/InnerGrep.java
> + * Данный класс повторяет функцию grep
Совсем комментарий не нужно было удалять

2020-06-08 22:07 UTC, aleksZubakov commented on src/main/java/itmo/karpenko/cli/InnerGrep.java
> +            pattern = Pattern.compile(toFind, Pattern.CASE_INSENSITIVE);
Я тут совсем фигню написал, ага, прошу прощения. Вижу компиляцию регулярки -- отправляю компилировать ее при загрузке класса.

`this.CASE_INSENSITIVE` -- имелось ввиду, что регулярка будет скомпилирована однажды и будем держать ее как поле класса, но это полная фигня, т.к., конечно, выражение вводится пользователем и никуда от компиляции при каждом запуске не деться.

2020-06-08 22:37 UTC, ottergottaott requested changes
По функциональности все отлично. Подсветка вхождений классно работает, по коду оставил немного комментариев.

Поправьте и работу можно засчитывать

2020-06-08 22:37 UTC, aleksZubakov commented on src/main/java/itmo/karpenko/cli/InnerGrep.java
> +            devider = ConsoleColors.CYAN  + "--\n" + ConsoleColors.RESET;
Код стал получше, но я вижу характерную проблему: Вы используете некоторые поля для передачи аргументов в функции, а не для хранения состояния. 

Например, `devider` устанавливается здесь и по-хорошему больше нигде не меняется. А используется только в `innerRun`, который вызывается только в этой функции. 

Понятное дело, что за такими вещами сложно уследить и человеку намного проще понять, если аргумент был передан явно

2020-06-08 22:37 UTC, aleksZubakov commented on src/main/java/itmo/karpenko/cli/InnerGrep.java
> +    void innerRun(InputStream inStream, PrintStream ouStream, String prefix) {
`private`?

2020-06-08 22:37 UTC, aleksZubakov commented on src/main/java/itmo/karpenko/cli/InnerGrep.java
> +        }
Можно раньше выйти из функции, тогда меньше вложенность будет:
```java
if (inStream != null) {
    innerRun(inStream, outStream, "");
    return;
}

for (int i = 1; i < commandLine.getArgs().length; i++) {
    ...
}
```

2020-06-08 22:37 UTC, aleksZubakov commented on src/main/java/itmo/karpenko/cli/InnerGrep.java
> +        }
Еще, конечно, вот эти ребята `new BufferedInputStream(new FileInputStream(file))` не закроются, если выпадет исключение. Не забывайте использовать try-with-resources

2020-06-08 22:37 UTC, aleksZubakov commented on src/main/java/itmo/karpenko/cli/InnerGrep.java
> +        }
if/else с единственным присваиванием в обеих ветках
```java
if (commandLine.getArgs().length == 2) {
    file = "";
} else {
    file = ConsoleColors.PURPLE + file + ConsoleColors.RESET;
}
```
смело можно заменять на тернарный оператор:
```java
file = commandLine.getArgs().length == 2 ? "" : ConsoleColors.PURPLE + file + ConsoleColors.RESET;
```

2020-06-08 22:37 UTC, aleksZubakov commented on src/main/java/itmo/karpenko/cli/InnerGrep.java
> +        }
Ну и внутри for цикла можно if/else инвертировать и прерывать выполнение, если файл не найден, так от вложенности тоже избавимся:
```java
if (!(new File(file)).exists()) {
    outStream.append(String.format(FILE_NOT_FOUND, file));
    continue;
}
```

2020-06-09 12:44 UTC, mkarpenkospb commented on src/main/java/itmo/karpenko/cli/InnerGrep.java
> +            devider = ConsoleColors.CYAN  + "--\n" + ConsoleColors.RESET;
Да, у меня есть желание сократить количество аргументов функции. 
Тут я исходила их того, что переменные форматирования - nLines, divider, всевозможные префиксы однозначно соответствуют объекту этого класса. Но с другой стороны это и просто переменные, которые можно передать как аргументы.  

Получается две стороны - или путаться от количества аргументов функции, или от того а что это за переменная и откуда она взялась.

2020-06-09 12:48 UTC, mkarpenkospb commented
Внесла исправления

2020-06-09 12:56 UTC, aleksZubakov commented
Хорошо, засчитываю

2020-09-12 17:33 UTC, merged